widgets = {
    # frames
    "frame_link": None,
    "frame_data_video": None,
    "frame_basic_download": None,
    "frame_download": None,
    "frame_path_download": None,
    "frame_setting_window": None,
    # labels
    "text_link": None,
    "text_title": None,
    "video_name": None,
    "text_autor": None,
    "video_author": None,
    "text_image": None,
    "path_text": None,
    "video_image": None,
    "text_radiobutton": None,
    "percentage_label": None,
    # buttons
    "button_clear": None,
    "button_ok": None,
    "button_download": None,
    # others
    "Progressbar": None,
    "Textbox_path_to_video": None,
    "switch": None,
    "Combobox_url": None
}
